branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - 'build (Linux-ARM64-Large)'
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions:
        apps: []
        users: []
        teams: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      required_signatures: true
      enforce_admins: true
      required_pull_request_reviews: true
      required_branch_pattern: '^(release-|hotfix-)'

  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - 'build (Linux-ARM64-Large)'
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions:
        apps: []
        users: []
        teams: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      required_signatures: true
      enforce_admins: true
      required_pull_request_reviews: true
