name: ⏳ 任务
description: 创建您的任务
title: '[⏳ Task] '
type: ⏳ Task

body:
  - type: dropdown
    id: module
    attributes:
      label: 请选择需求相关的模块
      options:
        - Components
        - Widgets
        - Schematics
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 你的功能请求是否与某个问题相关？请描述。
      placeholder: |
        **你的功能请求是否与某个问题相关？请描述。**
        清晰简洁地描述问题是什么。例如：当 [...] 时，我总是感到沮丧。

        **描述你想要的解决方案**
        清晰简洁地描述你想要发生的事情。

        **描述你考虑过的替代方案**
        清晰简洁地描述你考虑过的任何替代解决方案或功能。

        **其他上下文**
        在此添加有关功能请求的任何其他上下文或截图。
